---
stages:
  - syntax
  - unit
  - acceptance

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
  - bundle install --path vendor/bundle --jobs $(nproc)

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.5.1-Puppet ~> 6.0:
  stage: syntax
  image: ruby:2.5.1
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 6.0'

parallel_spec-Ruby 2.5.1-Puppet ~> 6.0:
  stage: unit
  image: ruby:2.5.1
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 6.0'

parallel_spec-Ruby 2.4.4-Puppet ~> 5.0:
  stage: unit
  image: ruby:2.4.4
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.0'

parallel_spec-Ruby 2.5.1-Puppet ~> 6.0:
  stage: acceptance
  image: ruby:2.5.1
  script:
    - bundle exec rake beaker
  variables:
    DOCKER_HOST: tcp://docker:2375
    GEM_BOLT: 'true'
    PUPPET_GEM_VERSION: '~> 6.0'
    PUPPET_INSTALL_TYPE: 'agent'
    BEAKER_debug: 'true'
    BEAKER_PUPPET_COLLECTION: 'puppet6'
    BEAKER_set: 'docker/centos-7'
    BEAKER_TESTMODE: 'apply'
