---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      bundler_args:
      dist: trusty
      env: PLATFORM=centos:puppet6
      rvm: 2.5.1
      script:
      - bundle exec rake 'litmus:provision[docker, centos:7]'
      - bundle exec rake 'litmus:install_agent[puppet6, localhost]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake 'litmus:install_module'
      - bundle exec rake 'litmus:acceptance:parallel'
      - bundle exec rake 'litmus:tear_down'
      services: docker
      sudo: required
notifications:
  email: true
